# Generated by Django 2.0 on 2017-12-25 21:15

from django.db import migrations, models
import readin.models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='inputfile',
            field=models.FileField(null=True, upload_to=readin.models.user_directory_path),
        ),
    ]
