# Generated by Django 2.0 on 2017-12-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='algorithm_choice',
            field=models.CharField(choices=[('Supervised', 'S'), ('Unsupervised', 'U')], default='Supervised', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
