# Generated by Django 2.0 on 2017-12-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0006_auto_20171226_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='algorithm_choice',
            field=models.CharField(default='S', max_length=2),
        ),
    ]
