# Generated by Django 2.0 on 2017-12-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0010_auto_20171227_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
