# Generated by Django 2.0 on 2017-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0011_auto_20171227_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='validation_split',
            field=models.DecimalField(decimal_places=1, default=75, max_digits=3),
        ),
    ]
