# Generated by Django 2.0 on 2017-12-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0012_post_validation_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method_super',
            field=models.CharField(choices=[('C', 'Classification'), ('R', 'Regression')], default='C', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='no_labels',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='post',
            name='target',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
