# Generated by Django 2.0 on 2017-12-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0013_auto_20171227_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='method_super',
            field=models.CharField(blank=True, choices=[('C', 'Classification'), ('R', 'Regression')], max_length=128),
        ),
    ]
