# Generated by Django 2.0 on 2017-12-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0015_auto_20171227_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method_unsuper',
            field=models.CharField(blank=True, choices=[('C', 'Clustering'), ('F', 'Feature Selection')], max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='no_clusters',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='post',
            name='no_features',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
