# Generated by Django 2.0 on 2017-12-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0016_auto_20171227_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='algorithm_choice',
            field=models.CharField(choices=[('S', 'Supervised'), ('U', 'Unsupervised')], max_length=2),
        ),
    ]
