# Generated by Django 2.0 on 2017-12-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0017_auto_20171228_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='algorithm_choice',
            field=models.CharField(choices=[('S', 'Supervised'), ('U', 'Unsupervised')], max_length=2, null=True),
        ),
    ]
