# Generated by Django 2.0 on 2017-12-28 15:59

from django.db import migrations, models
import readin.models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0020_auto_20171228_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='inputfile',
            field=models.FileField(blank=True, null=True, upload_to=readin.models.user_directory_path),
        ),
    ]
