# Generated by Django 2.0 on 2018-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0021_auto_20171228_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method_class',
            field=models.CharField(blank=True, choices=[('DT', 'Decision Tree'), ('SVM', 'Support Vector Machine'), ('NN', 'Neural Network'), ('LR', 'Logistic Regression')], max_length=128),
        ),
    ]
