# Generated by Django 2.0 on 2018-01-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0022_post_method_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method_reg',
            field=models.CharField(blank=True, choices=[('DT', 'Decision Tree'), ('NN', 'Neural Network'), ('LR', 'Linear Regression')], max_length=128),
        ),
    ]
