# Generated by Django 2.0 on 2018-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0023_post_method_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='method_reg',
            field=models.CharField(blank=True, choices=[('DT', 'Decision Tree'), ('BR', 'Bayesian Ridge'), ('LR', 'Linear Regression')], max_length=128),
        ),
    ]
