# Generated by Django 2.0 on 2018-01-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0024_auto_20180105_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='method_reg',
            field=models.CharField(blank=True, choices=[('DT', 'Decision Tree'), ('BR', 'Bayesian Ridge'), ('SVR', 'Support Vector Regression'), ('LR', 'Linear Regression')], max_length=128),
        ),
    ]
