# Generated by Django 2.0 on 2018-01-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0026_post_method_clust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='method_clust',
            field=models.CharField(blank=True, choices=[('KM', 'K-Means Clustering'), ('SC', 'Spectral Clustering'), ('AC', 'Agglomerative Clustering'), ('BC', 'Birch Clustering')], max_length=128),
        ),
    ]
