# Generated by Django 2.0 on 2018-01-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0027_auto_20180105_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='algorithm_choice',
            field=models.CharField(blank=True, choices=[('S', 'Supervised'), ('U', 'Unsupervised'), ('F', 'Feature Selection')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='method_unsuper',
            field=models.CharField(blank=True, choices=[('C', 'Clustering')], max_length=128),
        ),
    ]
