# Generated by Django 2.0 on 2018-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0028_auto_20180107_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hyper',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='method_hyper',
            field=models.CharField(blank=True, choices=[('GR', 'Grid Search CV'), ('RR', 'Randomized Search CV')], max_length=128),
        ),
    ]
