# Generated by Django 2.0 on 2018-02-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0029_auto_20180206_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_ensemble',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='method_ensemble',
            field=models.CharField(blank=True, choices=[('VC', 'Voting Classifier')], max_length=128),
        ),
    ]
