# Generated by Django 2.0 on 2018-02-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0030_auto_20180209_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='method_hyper',
        ),
    ]
