# Generated by Django 2.0 on 2018-02-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0033_auto_20180209_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='method_class_ensemble',
            field=models.CharField(blank=True, choices=[('AdaC', 'Ada Boost Classifier'), ('BC', 'Bagging Classifier'), ('ETC', 'Extra Trees Classifier'), ('GBC', 'Gradient Boosting Classifier'), ('RFC', 'Random Forest Classifier')], max_length=128),
        ),
    ]
