# Generated by Django 2.0 on 2018-02-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0034_auto_20180209_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method_reg_ensemble',
            field=models.CharField(blank=True, choices=[('AdaR', 'Ada Boost Regressor'), ('BR', 'Bagging Regressor'), ('ETR', 'Extra Trees Regressor'), ('GBR', 'Gradient Boosting Regressor'), ('RFR', 'Random Forest Regressor')], max_length=128),
        ),
    ]
