# Generated by Django 2.0 on 2018-02-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0037_auto_20180211_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='method_class',
            field=models.CharField(blank=True, choices=[('DT', 'Decision Tree'), ('SVM', 'Support Vector Machine'), ('NN', 'Neural Network'), ('LR', 'Logistic Regression')], max_length=128),
        ),
    ]
