# Generated by Django 2.0 on 2018-02-11 18:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0039_auto_20180211_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='method_class',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DT', 'Decision Tree'), ('SVM', 'Support Vector Machine'), ('NN', 'Neural Network'), ('LR', 'Logistic Regression')], max_length=12),
        ),
    ]
