# Generated by Django 2.0 on 2018-02-11 22:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0040_auto_20180211_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_class_ensemble',
        ),
        migrations.RemoveField(
            model_name='post',
            name='method_class_ensemble',
        ),
        migrations.AlterField(
            model_name='post',
            name='method_class',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DT', 'Decision Tree'), ('SVM', 'Support Vector Machine'), ('NN', 'Neural Network'), ('LR', 'Logistic Regression'), ('AdaC', 'Ensembled Ada Boost Classifier'), ('BC', 'Ensembled Bagging Classifier'), ('ETC', 'Ensembled Extra Trees Classifier'), ('GBC', 'Ensembled Gradient Boosting Classifier'), ('RFC', 'Ensembled Random Forest Classifier')], max_length=32),
        ),
    ]
