# Generated by Django 2.0 on 2018-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readin', '0044_auto_20180211_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_reg_ensemble',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='method_reg_ensemble',
            field=models.CharField(blank=True, choices=[('AdaR', 'Ada Boost Regressor'), ('BR', 'Bagging Regressor'), ('ETR', 'Extra Trees Regressor'), ('GBR', 'Gradient Boosting Regressor'), ('RFR', 'Random Forest Regressor')], max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='method_reg',
            field=models.CharField(blank=True, choices=[('DT', 'Decision Tree'), ('BR', 'Bayesian Ridge'), ('SVR', 'Support Vector Regression'), ('LR', 'Linear Regression')], max_length=128),
        ),
    ]
